---
title: "donate_rate"
output: html_document
date: "2024-02-29"
---

## 3 užduotis

```{r, include=FALSE}
library("sas7bdat")
setwd("C:/Users/User/Desktop/KTU/Duomenų_tvarkymas")
data = read.sas7bdat("donate.sas7bdat")
```

## Surasime sąlygines išskirtis 

```{r}
for ( i in 2:length(data))
{
  lower_bound <- quantile(data[i], 0.25,na.rm=T)
  upper_bound <- quantile(data[i], 0.75,na.rm=T)
  IQR=upper_bound-lower_bound
  a=which((data[i] <= lower_bound - 1.5*IQR & data[i] > lower_bound-3*IQR) | (data[i] > upper_bound + 1.5*IQR & data[i] <= upper_bound + 3*IQR))
  b=data[a, i]
}
```

## Surasime grubias išskirtis ir jas pašalinsime

```{r}
for ( i in 2:length(data))
{
  Q1 <- quantile(data[i], 0.25,na.rm=T)
  Q3 <- quantile(data[i], 0.75,na.rm=T)
  IQR=Q3-Q1
  a=which(data[i] < Q1 - 3*IQR | data[i] > Q3 + 3*IQR )
  b=data[a, i]
  data_clean = data[-a, ]
  data_clean
}
```
## Į tuščias reikšmes įstatome stulpelio vidurkį ir jas apvaliname

```{r}
data_clean$Qtr1[is.na(data_clean$Qtr1)] = round(mean(data_clean$Qtr1,na.rm=T), 0)
data_clean$Qtr2[is.na(data_clean$Qtr2)] = round(mean(data_clean$Qtr2,na.rm=T), 0)
data_clean$Qtr3[is.na(data_clean$Qtr3)] = round(mean(data_clean$Qtr3,na.rm=T), 0)
data_clean$Qtr4[is.na(data_clean$Qtr4)] = round(mean(data_clean$Qtr4,na.rm=T), 0)
data_clean
```

## Sukuriame naują stulpelį donate_rate ir jį apvaliname iki šimtųjų

```{r, include=FALSE}
library("dplyr")
```


```{r}
donations = sum(data_clean$Qtr1, data_clean$Qtr2, data_clean$Qtr3, data_clean$Qtr4)

data_clean %>%
  mutate(donate_rate = round(((Qtr1 + Qtr2 + Qtr3 + Qtr4) / donations * 100), 2))
```

